### ISSUE TITLE
How to use it with minicap?

### ISSUE THREAD

**Issue by KilmerZhao** [openstf/RotationWatcher.apk#1]
In README.md, I saw this sentence "While fairly useless by itself, it can be used together with other components such as minicap for screen capturing."

How to use it with monicap ?

When I use "adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 480x854@480x854/0" to start minicap and let the device to horizontal direction,the bufferimage is always vertical.

**Comment by sorccu** [comment]
You have to build an app by yourself that parses the output from RotationWatcher.apk and restarts minicap with new parameters when the rotation changes. STF does this, although the rotation watcher is embedded in [STFService.apk](https://github.com/openstf/STFService.apk) instead. Note that if the orientation of the picture doesn't seem to change, you may be running into  the [QUIRK_ALWAYS_UPRIGHT](https://github.com/openstf/minicap#quirk-bitflags) quirk.
